name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.5

  build:
    needs: ruby-versions
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-latest ]
        # CRuby < 2.6 does not support macos-arm64, so test those on amd64 instead
        exclude:
        - { os: macos-latest, ruby: '2.5' }
        include:
        - { os: macos-13, ruby: '2.5' }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        # In order to support Ruby 2.5, use a pre-2.4 Bundler.
        bundler: '2.3.26'
    - name: Run test
      run: bundle exec rake test
